export PYTHONIOENCODING=UTF-8
MAX_THREADS=3
export MKL_NUM_THREADS=$MAX_THREADS
export NUMEXPR_NUM_THREADS=$MAX_THREADS
export OMP_NUM_THREADS=$MAX_THREADS
export OPENBLAS_NUM_THREADS=$MAX_THREADS
export VECLIB_MAXIMUM_THREADS=$MAX_THREADS
export NCCL_IB_TIMEOUT=120
export NCCL_IB_GID_INDEX=3
export NCCL_DEBUG=INFO
export NCCL_IB_DISABLE=0
export NCCL_NET_PLUGIN=none
export GLOO_SOCKET_IFNAME=eth0

